<!DOCTYPE html>
<html>
    <head>
        <title>StuReg</title>
    </head>
    <body>
        <h1>Welocme to StuReg!</h1>
        <div>
            <button>
                <a href="students">Список студентов</a>
            </button>
        </div>
        <hr>
        <div>
            <button>
                <a href="univers">Список ВУЗов</a>
            </button>
        </div>
    </body>
</html>